---
title: Your Body in Space
hero_image: images/space-body-quiz.png
theme:  violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
description: Create a quiz to test your friend's knowledge of living in space.
original_url: https://codeclubprojects.org/en-GB/space-mission/space-body-quiz
interests: ''
technologies: scratch
site_areas: codeclub, space-mission
steps:
- title: Introduction
- title: Let's meet Marco
- title: Add the first question
- title: Add a score
- title: 'Challenge: Add more questions'

